spring.application.name: ingredients

logging:
  level.org.springframework.cloud: DEBUG
  level.org.springframework.cloud.sleuth: TRACE
  level.org.springframework.cloud.sleuth.log: DEBUG
  level.org.springframework.cloud.sleuth.trace: DEBUG
  level.org.springframework.cloud.sleuth.instrument.rxjava: DEBUG

server.port: ${PORT:9994}

spring.rabbitmq.host: ${RABBIT_HOST:localhost}

logging.file: build/ingredients.log

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
spring.cloud.stream.binder.rabbit.default.maxConcurrency: 5


endpoints.health.sensitive: false
endpoints.default.web.enabled: true
management.security.enabled: false
management.endpoints.web.base-path: /

spring.zipkin.sender.type: web