server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    renewal-percent-threshold: 0.01
    waitTimeInMsWhenSyncEmpty: 0

info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"