sudo: required
services:
  - docker
  - rabbitmq

language: groovy

jdk:
- oraclejdk8

install:
- true

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx256m"

script:
- ./gradlew clean build --parallel $SWITCH

env:
  global:
  - TERM=dumb
  - SHOULD_START_RABBIT=no
  - RETRIES=200
  matrix:
    - SWITCH='-DWHAT_TO_TEST=SLEUTH'
    - SWITCH='-DWHAT_TO_TEST=ZOOKEEPER'
    - SWITCH='-DWHAT_TO_TEST=EUREKA'
    - SWITCH='-DWHAT_TO_TEST=CONSUL'