apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: bookstore-instance
  namespace: test
  labels:
    run: bookstore-broker
spec:
  clusterServiceClassExternalName: bookstore
  clusterServicePlanExternalName: standard
  parameters:
    max: 10
