apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: bookstore-broker
  labels:
    run: bookstore-broker
spec:
  url: http://bookstore-broker.bookstore-broker.svc.cluster.local
  authInfo:
    basic:
      secretRef:
        name: bookstore-broker-secret
        namespace: catalog

