cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
script: ./mvnw --fail-at-end --update-snapshots clean install
notifications:
  slack:
    secure: oba1C58doySmrOhh1vFxccgp9JCQi1cNBKhC0YD5I9uk44eXAsOs8GjIs3wqfReKkSf4e9N8jRpbQWoIayQV/qRvkRJnpxuFv5q3Rtr4+S50Ie2IfrghRpphV7uyL3ktswyPHLTLVNxEW1cext9ZDOMb3S+Z4lwCz0gBjf9cZWGzBIsj6Wb0cr31Jo/xKuvBTwxRdTJGh20CvHXpXYeB/dNbY5BmlDP1Ys8dtP0/NrWTJ5/MG2BubaQ/xuUA+aw573XaYA+3t6vDVEfedNcDO8oNcQgp9zpp3p5Z4pipqKGyrqQAp/xnRt73TGRl6XQ9t/ZGdOSz6vSHaaVhtBKkOpoW8DxQ9nq9GWOK7R9r1ok919blzSfZvjJ5jUVM931XaUhIfWbv1f/UGgFRJSJ/G81s27trd0GCYXPXyq1tFVQBp/CxrBwuOfPtE7rTwFaFM4eo6tgwkbHFW4ZXJWk5MXWhkgRM7Frqq5mMophz6YT2suuEYgYVM7f0l2lXAC/O7PkobMzbeDRiMwREx5KBKGd6GFpmKfUua8b75nOcn9UB4aDtdCb70LwBCVotvQT0rKk1zxLp28iNilk1HQubfOG9S5gjjuqsXPfHgsmzA2CnQbj1yjansGXA8uq0NBOBUo2lvopsXGBw0tJNj53DY5sxd3jXaNIYQjsGT2knHp0=
