sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: kvXXhR3YPlk6heAvPRIuT6IEpiPJibS89/u+yMmCvS0EZZxwZra/cC9AtIzhfUHcKF2//F3r9NdIegxYBUhe/Sw5owA1WydIfw+BAQ5G6x8wlMa+upgTO0cW5fIuoGjP+S2816dDMtjk0u3wy2jRS5psubdBMldfi4vzoKy9qGehMKghR5jEPvZhLQlr/B9zJLMA3IEmnvuyzGXifcvSZ7VYcq1OnXX7Up10KZgtlqcL9RXBdKSC1deuZjCgDdvoql8R1PITpGs0+prVk7A4G5oJ3hrSy3RdIG5vla8WLS0/thS0ss65iCY3Y9JsRGg4tUsVFMJtzH9h8AjTY82Sf8Pi2H4AFXTGU8P/SYZe6ZlGAUHEfh76bR7Mk90558JxgSQ1kss2nqt/honkCOVX2CW0FjpqgD6xvguTNrUUAQxqPjaifw4OqSmkxsKcByfq0U8qUqWob4K3LCeGTu1swkJ6ZFLxTP8u8wj9q/u7RJHFtFye9spQYLi5IdNEafLEAL4TbYdIfZHPFcR1aJWx0JzD8SIdIIJIGwZdedikoXLEKtok6+HZKaZS+xNMyVGmQby9qd95ZEYL+NWynTyflHJ5VJI7rz2QnY8E0p6shCmWXQQydGiBlSFvkJ5+jSUU8YNDTmjYuI66ilkxZZ3UWWw/PIun6S7CSz2i4SANA6U=
