language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: Gco/Lo3Ho5rGdabL3vOy+LemOQ/MosRAf6UCUMD5AeAnwML0+uLPrZzUSJX5LquVVzsRCfnoiwly/Ta/HyMHtdzxUwOI+U6G4RYFexxNwEiXgazvmwyUc5ggJjJCwga5SW8f/7bKyEHiIHYQjMYmowUvuZ1yEB6KcIYfaUrrMJZdPtLMIQ/78aqh2LdqlgAlX2YPI3ra7hLVa0h19b6StLDTc1EFkN1aJvaDdgHA6btSwjN1K6jHfH7Sq/doKN3xQ/jQfIwLDpobrwmx6sQOMdB0O0kHCN+t4NMJ8vZNOIWgkXA7eCHZ6g7y1r6KMeVMmvq4RavcaKskZyxTNOLxB5cngNSao7LejGgNwareDmYh13Pfm9o4z3fVIEhfg8A+2qOHnkkYDynrZjiPhq+FIm0Fp0cgl/NhjKF1hNi+4X3yz0ABxZbhCGsOiug/CkEDYMJ7jZy4s+8dUv7NmHljIBjpZG3e0q/OCDPPlh52u2TL4D/PvFxv05cNiHSNRiO8v2fayBvrIWsIJrqc81ExwwCWNFeOFb2N/MtRB8n4Zt6inbzpr6AyGrd3xCtMNL3anxLiHYmwU315qSqrUgi/1UYqbEC6MA+jbS3mDYiWRvPW1c5LzqTygqOlAUDAoFui7hurPUDNiGq19bwyZi/GejBXPz1T6+808tuysHMEEnQ=
