management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles:
    active: cloud
  datasource:
    url: ${vcap.services.broker-db.credentials.jdbcurl:jdbc:hsqldb:mem:broker-db}
    username: ${vcap.services.broker-db.credentials.username:sa}
    password: ${vcap.services.broker-db.credentials.password:}