language: java
servers:
  - redis-server
before_install: git clone https://github.com/dsyer/spring-security-rsa tmp && (cd tmp && mvn install -DskipTests=true)
script: mvn package -nsu -Dmaven.test.redirectTestOutputToFile=true
