server:
  port: 3380

spring:
  application:
    # This ends up as the service name in zipkin
    name: testsleuthzipkin
  #zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    # baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      probability: 1.0

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false
