sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: BjHDpeo5buCK3U+HpCcFiu+vyGCunhvsFjS3zUVyemLfKuW/vwm0Rt33J3LgL6R8ih50MVVu5yNqZe5ykgLOURrlgdPsKl+Gn4nvcHW7WGi5Rpdw/fnZkHHu6W356dxSqQifOa+pIH7sVnQrymXdddH6ujmUqpbF93KKxLB3Kph38+NX/JdwDEfNZdt4YbYLf3533nKcN/g1FO8b1Y/UtEcFtUhzgse4WhvE7L4q//w/Ctk1BOdUjHdRKBKJKqo/5fVCc1g10RrrYcNnp5PrboDjM6YM6RSyH3XS/r/hX+wloWuExGYR4jVxAyR0yJ0NlWcyv+7q/4tWiGmXbi0ZDCytEgrOgYOO/ieX4/1TxHRBJBeQblGGGMpiWqwxEe4H7vd2AjTPjUlbXcFKfhagBsNHcPVy367FFu/cvRyKokvArcUm+KGyPVcGh6dpw9SHRWxSvExL1fuMFvPxJWXn2EcuZTvqhAhDRc92wl8p4/CWAhPytLCQLQuPta8pL5Q5sDFpAn4HgNjSJ4OINqWo0qLBTU09mT1uy0Gq2FU7wQ9YfavoDyVVofTXyvpGz39WPJB8o4Sr7smdUxLGWEQrs1ScQyZ+5uwK7VA44ZgZBJmJa7KFO5+7vG0oGRFJQ9nBT1TIyUvytbI6Z+ZgYZ3Xh7FxjOeIXeglV7sKFbIVEdQ=
