version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:
  cassandra:
    image: cassandra
    ports:
    # 7000: intra-node communication
    # 7001: TLS intra-node communication
    # 7199: JMX
    # 9042: CQL
    # 9160: thrift service
    - "9042:9042"
    volumes:
    - cassandradata:/var/lib/cassandra
    
  redis:
    image: redis
    ports:
      - "6379:6379"
      
  mongodb: 
    image: mongo 
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --smallfiles 
#   command: --smallfiles --rest --auth  // if there is a password set in mongo.

  couchbase:
    image: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbasedata:/opt/couchbase/var
volumes:
  mongodata:  
#    driver: local-persist
#    driver_opts:
#      mountpoint: ./data  
  cassandradata: 
  couchbasedata: 
       