spring:
  application:
    name: consumer-feign-hystrix-stream
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
feign:
  hystrix:
    enabled: true