spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service_customer
          uri: lb://CONSUMER
          order: 0
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
#            - Retry=5
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
      default-filters:
        - Elapsed=true
      httpclient:
        pool:
          acquire-timeout: 10000
  redis:
    host: localhost
    port: 6379
    database: 0
server:
  port: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.windmt.filter: debug
management:
  endpoints:
    web:
      exposure:
        include: "*"