language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: Gxk8telmCqynsHzvMJNT5s12vBUPotfQBlOjgHj6Brsyrxz0WpsZgcnGhG5sqve1cyr4PrKv0coWR2uqc2PIOU2ZhtYW5sHzLjd+fyPv334uUqJRvY0+6eewIfpsx2CNUHl43c3W+ASik1cysysB5H1Olo8TbjLhINA4o7/mysOdYx0S2LU7HPltRBsA84YCScNawGHB7HpyUKaK/9yQjC0qejWKVTwvTxXpGFQXqxPCYSgZ2Ey0CqfGCxGu4G5B1pGLJA3MnSmuz9twa4O6PkqDhvEQzIcz7Bm4mrB32LB79Ffo5JRwhbu5r0tpV5bdVxxi0rajoswUPVu5vYQfuz74zdO/Jm7mziYCj1a12J/RzIWlfGAKnNt5T5YLlMZWO+Q4Ff5TZQWrfFqA4I1VVJoMGavc9Yj0aAyfMSRX5nwLYv2SOpKj9emdyvQiVcB3sBbDhcFGvH5JKTq3Hmrt/UW94ceCTIGpG7vrCuCCs3mf7+AUO7n+7OOcz780l8MUefHstEKdH/1i2jutrmy3rjzl8c/DBfpcNvjc+LxP/b8iAQP2u1n7r+PYF298w2a++5GUf7zF2Wdb8/RHU2JnFblnCed6oMdDcd46CkCCwvFVlWUTgKtSmTaZjHfn38L2gyL3fIrxz8calMI8n3VD8S4xZ19/TqxBXe1+zoNAgWA=
