sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: qLcISHcA/5iuW8RtMKBs7p82w0hGqsaNYrvNpUuSLfhgK8+xoLU7CNKcvdSp2BSvBnfJyMKYilRj3aTsECKAyElpnXnFMTW5ikInvGSNTrG19mYhRE1S6HtWjOFTGxIzTs45CKRCdfi9EivXLp6IosDPWBMA4+wbs/vIFU5NQSFVwYImXkKGz3Pu5H3ZcfKiSofzru6NgGLYGYVOr4Odv+TcCwijoObvcLitHmbvjzZzFa7F64MwBEqdTwarUnmczkvKP/CTGR1/bgfChkQFTVmRnhGlrnpS9kvJI/M9jtG4WGFFgma++B5bMrENoq4OTsxTt3psc4Yza3pGsUGNf3koAM/Yu7JWxxZueE64s4kwC3ZDYQ9nqvCL9Qlvv5kbdA1OoCaTwgMVKsqtitZdYOYjMk2qOhQunzCA8mtaeayxuMBknTVq2kIuhhY35XWL4ei4aUDT0eCAZl9Y2yDcSISLfxwtEbVxnXU/s5k0/bi1nKokEMtbWLHCHaY6e6ppu4RApS1ZfK5DUG7ige38HpkevXS2zGgTfd6IgP5PJMluBx7Hmk27qGV2HpXQUV2ISrSpZBHj5lxeUmnrBexx76MwFXBJJmmtBhuf/sLyp6St6KMpQ6vMx9Rcw2yda42nmbrv/ydOWma5k33Cy8lhlP0Z83xYN3g8yCYmlbyBUNU=
