spring:
  application:
    name: eureka-server
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
security:
  basic:
    enabled: true #开启认证
  user:
    name: user
    password: 123456